### ISSUE TITLE
Document departures from nano's behavior

### ISSUE THREAD

**Issue by dmd** [pgengler/pinot#26]
I would like to see some documentation of in what ways pinot departs from nano's behavior, both currently and planned.

**Comment by Efreak** [comment]
:+1:

**Comment by pgengler** [comment]
I've started putting together a [https://github.com/pgengler/pinot/wiki/Differences-from-nano](Github wiki page) to document the differences. It basically just covers user-facing differences; there are some internal differences but for the most part they don't matter.

If you come across anything that seems to be missing, feel free to add it, or to open a new issue to clarify whether the difference is intentional or not.
